version: "3.8"

services:
  isulogger-app:
    container_name: isulogger-app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "8083:8080"

  isulogger-server:
      container_name: isulogger-server
      build:
        context: ./server
        dockerfile: Dockerfile
      restart: always
      tty: true
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      depends_on:
        - isulogger-db
      volumes:
        - ./server:/go/src/app
      ports:
        - "8082:8082"

  isulogger-db:
    container_name: isulogger-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgres: