version: "3.8"

services:
  isulogger-app:
      container_name: isulogger-app
      build:
        context: ./webapp
        dockerfile: Dockerfile
      restart: always
      tty: true
      volumes:
        - ./webapp:/go/src/app
      ports:
        - "8082:8082"