version: "3.8"

services:
  isulogger-app:
      container_name: isulogger-server
      build:
        context: ./server
        dockerfile: Dockerfile
      restart: always
      tty: true
      volumes:
        - ./server:/go/src/app
      ports:
        - "8082:8082"