version: "3.8"

services:
  isulogger-app:
    container_name: isulogger-app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "127.0.0.1:8083:8080"

  isulogger-server:
      container_name: isulogger-server
      build:
        context: ./server
        dockerfile: Dockerfile
      restart: always
      tty: true
      environment:
        DB_PATH: /data/db.sqlite3
      volumes:
        - ./server:/go/src/app
        - ./data:/data
      ports:
        - "127.0.0.1:8082:8082"
